apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-no-access-binding
  namespace: studentqna
subjects:
- kind: ServiceAccount
  name: frontend-sa
  namespace: studentqna
roleRef:
  kind: Role
  name: frontend-no-access
  apiGroup: rbac.authorization.k8s.io
