name: CI - Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: users/StudentQnA.Users.ApiTests
        run: dotnet restore

      - name: Build solution
        working-directory: users/StudentQnA.Users.ApiTests
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests with coverage
        working-directory: users/StudentQnA.Users.ApiTests
        run: |
          dotnet test \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/coverage.opencover.xml \
            /p:CoverletOutputFormat=opencover

      - name: Collect Coverage
        working-directory: users/StudentQnA.Users.ApiTests
        run: dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Debug coverage files
        working-directory: users/StudentQnA.Users.ApiTests
        run: |
          echo "Coverage files found:"
          find . -name "*.xml"
          find . -name "*.coverage*"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: users/StudentQnA.Users.Api
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.cs.vstest.reportsPaths=../StudentQnA.Users.ApiTests/TestResults/*.trx
            -Dsonar.coverageReportPaths=../StudentQnA.Users.ApiTests/TestResults/*/coverage.opencover.xml
